server {
	listen 80;
	server_name my_url.com www.my_url.com;
	
	location / {
		include proxy_params;
		proxy_pass http://unix:/home/tony/hike/peak.sock;
	}
}

# create sim link from /etc/nginx/sites-available/peal.conf to /etc/nginx/sites-enabled/

# ln -s

# sudo nginx -t
# sudo systemctl restart nginx

# sudo ufw delete allow 5000
# sudo ufw allow "Nginx Full"
# sudo ufw status

# permissions issue: bad gateway
# sudo tail /var/log/nginx/error.log
# sudo chmod 775 /home/tony/
